AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

require:
 - ./lib/balse.rb
 - rubocop-rspec
 - some-unpermitted-plugin

inherit_from: .rubocop4.yml

inherit_gem:
 my-shared-gem: .rubocop4.yml
 cucumber: .rubocop4.yml

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
