AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

require:
 - ./lib/balse.rb
 - rubocop-rspec
 - some-unpermitted-plugin

inherit_from:
 - http://www.example.com/rubocop.yml
 - ../.rubocop.yml

inherit_gem:
 my-shared-gem: .rubocop.yml
 cucumber: conf/rubocop.yml

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
