AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true


require:
 - ./lib/balse.rb
 - rubocop-rspec
 - some-unpermitted-plugin

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
