AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

require:
 - ./lib/balse.rb
 - rubocop-rspec
 - some-unpermitted-plugin

inherit_from:
 - http://www.example.com/rubocop.yml
 - .rubocop2.yml

inherit_gem:
 my-shared-gem: .rubocop2.yml
 cucumber: .rubocop2.yml

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false
