AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true

# シングルクォートよりもダブルクォート
Style/StringLiterals:
  EnforcedStyle: double_quotes

# private / protected のメソッドは一段深くする
Style/IndentationConsistency:
  EnforcedStyle: rails
